controller_list:
  - name: fake_robot_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - joint1
      - joint01
      - joint2
      - joint3
      - joint4
      - joint5
  - name: fake_robot_hand_controller
    type: $(arg fake_execution_type)
    joints:
      - joint7
initial:  # Define initial robot poses per group
  - group: robot_arm
    pose: home